### ISSUE TITLE
I/O Error

### ISSUE THREAD

**Issue by agentace** [beli-sk/IMU_sensors#1]
Attempting to use your class to read the ADXL345 yields:
Traceback (most recent call last):
  File "accel.py", line 17, in <module>
    sensor.default_init()
  File "/home/pi/adxl345.py", line 88, in default_init
    self.data_format(False, 2)
  File "/home/pi/adxl345.py", line 54, in data_format
    self.bus.write_byte_data(self.addr, 0x31, fr_bit | range_bits[range])
IOError: [Errno 5] Input/output error

**Comment by agentace** [comment]
Please disregard:  I used the values for SensorADXL345() you used in your example.
I'm using a Revision 1 RPi, so instead of:
sensor = SensorADXL345(1, 0x53)
I needed to use:
sensor = SensorADXL345(0, 0x53)

Everything is working now.  Thanks for the great code!
